/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.28
 * Generated at: 2018-05-03 04:41:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Managers_005fHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head id=\"Head1\">\n");
      out.write("<title>渭南石羊企业生猪养殖信息系统</title>\n");
      out.write("<link href=\"index/css/default.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"index/js/themes/default/easyui.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"index/js/themes/icon.css\" />\n");
      out.write("<script type=\"text/javascript\" src=\"index/js/jquery-1.4.2.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"index/js/jquery.easyui.pack.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src='index/js/outlook2.js'>\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar _menus = {\n");
      out.write("\t\t\"menus\" : [ {\n");
      out.write("\t\t\t\"menuid\" : \"1\",\n");
      out.write("\t\t\t\"icon\" : \"icon-sys\",\n");
      out.write("\t\t\t\"menuname\" : \"供应商管理\",\n");
      out.write("\t\t\t\"menus\" : [ {\n");
      out.write("\t\t\t\t\"menuname\" : \"猪苗供应商\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-users\",\n");
      out.write("\t\t\t\t\"url\" : \"store_zhumiao.html\"\n");
      out.write("\t\t\t}, {\n");
      out.write("\t\t\t\t\"menuname\" : \"饲料供应商\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-users\",\n");
      out.write("\t\t\t\t\"url\" : \"store_siliao.html\"\n");
      out.write("\t\t\t}, {\n");
      out.write("\t\t\t\t\"menuname\" : \"药品供应商\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-users\",\n");
      out.write("\t\t\t\t\"url\" : \"store_yaopin.html\"\n");
      out.write("\t\t\t} ]\n");
      out.write("\t\t}, {\n");
      out.write("\t\t\t\"menuid\" : \"2\",\n");
      out.write("\t\t\t\"icon\" : \"icon-sys\",\n");
      out.write("\t\t\t\"menuname\" : \"猪只管理\",\n");
      out.write("\t\t\t\"menus\" : [ {\n");
      out.write("\t\t\t\t\"menuname\" : \"猪只购入合同\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-remove\",\n");
      out.write("\t\t\t\t\"url\" : \"zhuzhi_contract.html\"\n");
      out.write("\t\t\t}, {\n");
      out.write("\t\t\t\t\"menuname\" : \"销售情况\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-remove\",\n");
      out.write("\t\t\t\t\"url\" : \"zhuzhi_xiaoshou.html\"\n");
      out.write("\t\t\t} , {\n");
      out.write("\t\t\t\t\"menuname\" : \"死亡记录\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-remove\",\n");
      out.write("\t\t\t\t\"url\" : \"zhuzhi_siwang.html\"\n");
      out.write("\t\t\t}, {\n");
      out.write("\t\t\t\t\"menuname\" : \"生病记录\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-remove\",\n");
      out.write("\t\t\t\t\"url\" : \"zhuzhi_shengbing.html\"\n");
      out.write("\t\t\t}, {\n");
      out.write("\t\t\t\t\"menuname\" : \"喂养记录\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-remove\",\n");
      out.write("\t\t\t\t\"url\" : \"zhuzhi_weiyang.html\"\n");
      out.write("\t\t\t}]\n");
      out.write("\t\t}, {\n");
      out.write("\t\t\t\"menuid\" : \"3\",\n");
      out.write("\t\t\t\"icon\" : \"icon-sys\",\n");
      out.write("\t\t\t\"menuname\" : \"猪场管理\",\n");
      out.write("\t\t\t\"menus\" : [ {\n");
      out.write("\t\t\t\t\"menuname\" : \"饲料领用\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-remove\",\n");
      out.write("\t\t\t\t\"url\" : \"zhuchang_siliao.html\"\n");
      out.write("\t\t\t}, {\n");
      out.write("\t\t\t\t\"menuname\" : \"药品领用\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-remove\",\n");
      out.write("\t\t\t\t\"url\" : \"zhuchang_yaopin.html\"\n");
      out.write("\t\t\t}, {\n");
      out.write("\t\t\t\t\"menuname\" : \"物料采用\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-remove\",\n");
      out.write("\t\t\t\t\"url\" : \"zhuchang_wuliao.html\"\n");
      out.write("\t\t\t}, {\n");
      out.write("\t\t\t\t\"menuname\" : \"猪场职工信息\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-remove\",\n");
      out.write("\t\t\t\t\"url\" : \"zhuchang_zhigong.html\"\n");
      out.write("\t\t\t}  ]\n");
      out.write("\t\t}, {\n");
      out.write("\t\t\t\"menuid\" : \"4\",\n");
      out.write("\t\t\t\"icon\" : \"icon-sys\",\n");
      out.write("\t\t\t\"menuname\" : \"客户管理\",\n");
      out.write("\t\t\t\"menus\" : [ {\n");
      out.write("\t\t\t\t\"menuname\" : \"客户信息管理\",\n");
      out.write("\t\t\t\t\"icon\" : \"icon-users\",\n");
      out.write("\t\t\t\t\"url\" : \"client_clientinfo.html\"\n");
      out.write("\t\t\t}]\n");
      out.write("\t\t} ]\n");
      out.write("\t};\n");
      out.write("\n");
      out.write("\n");
      out.write("\t$(function() {\n");
      out.write("\n");
      out.write("\t\topenPwd();\n");
      out.write("\t\t//\n");
      out.write("\t\t$('#editpass').click(function() {\n");
      out.write("\t\t\t$('#w').window('open');\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$('#btnEp').click(function() {\n");
      out.write("\t\t\tserverLogin();\n");
      out.write("\t\t})\n");
      out.write("\n");
      out.write("\t\t$('#btnCancel').click(function() {\n");
      out.write("\t\t\tclosePwd();\n");
      out.write("\t\t})\n");
      out.write("\n");
      out.write("\t\t$('#loginOut').click(function() {\n");
      out.write("\t\t\talert(\"dmeo\");\n");
      out.write("\t\t\t$.messager.confirm('系统提示', '您确定要退出本次登录吗?', function(r) {\n");
      out.write("\n");
      out.write("\t\t\t\tif (r) {\n");
      out.write("\t\t\t\t\tlocation.href = 'login.jsp';\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t})\n");
      out.write("\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\"easyui-layout\" style=\"overflow-y: hidden\" scroll=\"no\">\n");
      out.write("\t<noscript>\n");
      out.write("\t\t<div\n");
      out.write("\t\t\tstyle=\"position: absolute; z-index: 100000; height: 2046px; top: 0px; left: 0px; width: 100%; background: white; text-align: center;\">\n");
      out.write("\t\t\t<img src=\"index/images/noscript.gif\" alt='抱歉，请开启脚本支持！' />\n");
      out.write("\t\t</div>\n");
      out.write("\t</noscript>\n");
      out.write("\t<div region=\"north\" split=\"true\" border=\"false\"\n");
      out.write("\t\tstyle=\"overflow: hidden; height: 30px; background: url(index/images/layout-browser-hd-bg.gif) #7f99be repeat-x center 50%; line-height: 20px; color: #fff; font-family: Verdana, 微软雅黑, 黑体\">\n");
      out.write("\t\t<span style=\"float: right; padding-right: 20px;\" class=\"head\">欢迎\n");
      out.write("\t\t\t<font color=\"red\">");
      out.print(session.getAttribute("adminName"));
      out.write("</font> <a href=\"#\" id=\"loginOut\">安全退出</a>\n");
      out.write("\t\t</span> <span style=\"padding-left: 10px; font-size: 16px;\"><img\n");
      out.write("\t\t\tsrc=\"index/images/blocks.gif\" width=\"20\" height=\"20\"\n");
      out.write("\t\t\talign=\"absmiddle\" />渭南石羊企业生猪养殖信息系统</span>\n");
      out.write("\t</div>\n");
      out.write("\t<div region=\"south\" split=\"true\"\n");
      out.write("\t\tstyle=\"height: 30px; background: #D2E0F2;\"></div>\n");
      out.write("\t<div region=\"west\" split=\"true\" title=\"导航菜单\" style=\"width: 180px;\"\n");
      out.write("\t\tid=\"west\">\n");
      out.write("\t\t<div class=\"easyui-accordion\" fit=\"true\" border=\"false\">\n");
      out.write("\t\t\t<!--  导航内容 -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"mainPanle\" region=\"center\"\n");
      out.write("\t\tstyle=\"background: #eee; overflow-y: hidden\">\n");
      out.write("\t\t<div id=\"tabs\" class=\"easyui-tabs\" fit=\"true\" border=\"false\">\n");
      out.write("\t\t\t<div title=\"欢迎使用\" style=\"padding: 20px; overflow: hidden;\" id=\"home\">\n");
      out.write("\n");
      out.write("\t\t\t\t<h1>欢迎使用</h1>\n");
      out.write("\t\t\t\t<h1>渭南石羊企业生猪养殖信息系统</h1>\n");
      out.write("\t\t\t\t<p>左侧为菜单栏</p>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div id=\"mm\" class=\"easyui-menu\" style=\"width: 150px;\">\n");
      out.write("\t\t<div id=\"mm-tabclose\">关闭</div>\n");
      out.write("\t\t<div id=\"mm-tabcloseall\">全部关闭</div>\n");
      out.write("\t\t<div id=\"mm-tabcloseother\">除此之外全部关闭</div>\n");
      out.write("\t\t<div class=\"menu-sep\"></div>\n");
      out.write("\t\t<div id=\"mm-tabcloseright\">当前页右侧全部关闭</div>\n");
      out.write("\t\t<div id=\"mm-tabcloseleft\">当前页左侧全部关闭</div>\n");
      out.write("\t\t<div class=\"menu-sep\"></div>\n");
      out.write("\t\t<div id=\"mm-exit\">退出</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
