/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.28
 * Generated at: 2018-05-02 13:18:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ManageAnnouncement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-cn\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>主页</title>\n");
      out.write("<script src=\"eui/jquery.min.js\"></script>\n");
      out.write("<script src=\"eui/jquery.easyui.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"eui/themes/icon.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"eui/themes/default/easyui.css\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#fm {\n");
      out.write("\tmargin: 0;\n");
      out.write("\tpadding: 10px 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".ftitle {\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("\tpadding: 5px 0;\n");
      out.write("\tmargin-bottom: 10px;\n");
      out.write("\tborder-bottom: 1px solid #ccc;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".fitem {\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".fitem label {\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\twidth: 80px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".fitem input {\n");
      out.write("\twidth: 160px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("\tvar url;\n");
      out.write("\t//对话框OK选项\n");
      out.write("\n");
      out.write("\tfunction saveAnnouncement() {\n");
      out.write("\t\t$('#fm').form('submit', {\n");
      out.write("\t\t\turl : url,\n");
      out.write("\t\t\tonSubmit : function() {\n");
      out.write("\t\t\t\treturn $(this).form('validate');\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess : function(result) {\n");
      out.write("\t\t\t\tvar result = eval('(' + result + ')');\n");
      out.write("\t\t\t\tif (result.errorMsg) {\n");
      out.write("\t\t\t\t\t$.messager.show({\n");
      out.write("\t\t\t\t\t\ttitle : 'Error',\n");
      out.write("\t\t\t\t\t\tmsg : result.errorMsg\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t$('#dlg').dialog('close'); // close the dialog\n");
      out.write("\t\t\t\t\t$('#dg').datagrid('reload'); // reload the user data\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction editAnnouncement() {\n");
      out.write("\t\tvar row = $('#dg').datagrid('getSelected');\n");
      out.write("\t\tif (row) {\n");
      out.write("\t\t\t$('#dlg').dialog('open').dialog('setTitle', '编辑信息');\n");
      out.write("\t\t\t$('#fm').form('load', row);\n");
      out.write("\t\t\turl = 'updateAnnouncementAction?id=' + row.aid;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction destroyAnnouncement() {\n");
      out.write("\t\tvar ids = [];\n");
      out.write("\t\tvar rows = $(\"#dg\").datagrid('getSelections');\n");
      out.write("\t\tfor (var i = 0; i < rows.length; i++) {\n");
      out.write("\t\t\tids.push(rows[i].aid);\n");
      out.write("\t\t}\n");
      out.write("\t\tvar ids = ids.toString();\n");
      out.write("\t\tif (rows) {\n");
      out.write("\t\t\t$.messager.confirm('确定', '确定删除这个信息？', function(r) {\n");
      out.write("\t\t\t\tif (r) {\n");
      out.write("\t\t\t\t\t$.post('deleteAnnouncementAction', {\n");
      out.write("\t\t\t\t\t\tids : ids\n");
      out.write("\t\t\t\t\t}, function(result) {\n");
      out.write("\t\t\t\t\t\tif (result.success) {\n");
      out.write("\t\t\t\t\t\t\t$(\"#dg\").datagrid('reload');\n");
      out.write("\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\t$.messager.show({\n");
      out.write("\t\t\t\t\t\t\t\tTitle : '错误',\n");
      out.write("\t\t\t\t\t\t\t\tmsg : result.errorMsg\n");
      out.write("\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}, 'json');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t})\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("\t$(function() {\n");
      out.write("\t\tvar row = $('#dg').datagrid('getSelected');\n");
      out.write("\t\t$('#dg')\n");
      out.write("\t\t\t\t.datagrid(\n");
      out.write("\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\ttitle : '客户信息管理',\n");
      out.write("\t\t\t\t\t\t\ticonCls : 'icon-edit',\n");
      out.write("\t\t\t\t\t\t\twidth : 960,\n");
      out.write("\t\t\t\t\t\t\theight : 450,\n");
      out.write("\t\t\t\t\t\t\tsingleSelect : true,\n");
      out.write("\t\t\t\t\t\t\tidField : 'usernumber',\n");
      out.write("\t\t\t\t\t\t\turl : 'displayAnnouncementAction',\n");
      out.write("\t\t\t\t\t\t\tcolumns : [ [\n");
      out.write("\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfield : 'title',\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle : '客户来源',\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth : 50\n");
      out.write("\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfield : 'people',\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle : '客户名称',\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth : 50\n");
      out.write("\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfield : 'pubdate',\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle : '合作时间',\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth : 50\n");
      out.write("\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfield : 'action',\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle : '操作',\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth : 70,\n");
      out.write("\t\t\t\t\t\t\t\t\t\talign : 'center',\n");
      out.write("\t\t\t\t\t\t\t\t\t\tformatter : function(value, row, index) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar e = '<a href=\"Announcement.jsp?aid='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ row.aid\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ '\" onclick=\"#\" id=\"edit\">操作</a> ';\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar d = '';\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn e + d;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t} ] ],\n");
      out.write("\t\t\t\t\t\t\tonBeforeEdit : function(index, row) {\n");
      out.write("\t\t\t\t\t\t\t\trow.editing = true;\n");
      out.write("\t\t\t\t\t\t\t\tupdateActions(index);\n");
      out.write("\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\tonAfterEdit : function(index, row) {\n");
      out.write("\t\t\t\t\t\t\t\trow.editing = false;\n");
      out.write("\t\t\t\t\t\t\t\tupdateActions(index);\n");
      out.write("\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\tonCancelEdit : function(index, row) {\n");
      out.write("\t\t\t\t\t\t\t\trow.editing = false;\n");
      out.write("\t\t\t\t\t\t\t\tupdateActions(index);\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\tfunction updateActions(index) {\n");
      out.write("\t\t$('#dg').datagrid('updateRow', {\n");
      out.write("\t\t\tindex : index,\n");
      out.write("\t\t\trow : {}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction getRowIndex(target) {\n");
      out.write("\t\tvar tr = $(target).closest('tr.datagrid-row');\n");
      out.write("\t\treturn parseInt(tr.attr('datagrid-row-index'));\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction editrow(target) {\n");
      out.write("\t\t$('#dg').datagrid('beginEdit', getRowIndex(target));\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction saverow(target) {\n");
      out.write("\t\t$('#dg').datagrid('endEdit', getRowIndex(target));\n");
      out.write("\t\tvar row = $('#dg').datagrid('getSelected');\n");
      out.write("\t\t$.post(\"usePointAction\", {\n");
      out.write("\t\t\t\"point\" : row.bound\n");
      out.write("\t\t}, function(res) {\n");
      out.write("\t\t\tif (res.success) {\n");
      out.write("\t\t\t\t$.messager.show({\n");
      out.write("\t\t\t\t\tTitle : '成功',\n");
      out.write("\t\t\t\t\tmsg : '成功'\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\t$.messager.show({\n");
      out.write("\t\t\t\t\tTitle : '错误',\n");
      out.write("\t\t\t\t\tmsg : '失败'\n");
      out.write("\t\t\t\t})\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}, 'json');\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction cancelrow(target) {\n");
      out.write("\t\t$('#dg').datagrid('cancelEdit', getRowIndex(target));\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<table id=\"dg\" class=\"easyui-datagrid\"\n");
      out.write("\t\tstyle=\"width: 100%; height: 100%\"\n");
      out.write("\t\tdata-options=\"rownumbers:true,singleSelect:true,pagination:true\"\n");
      out.write("\t\turl=\"displayAnnouncementAction\" toolbar=\"#toolbar\" rownumbers=\"true\"\n");
      out.write("\t\tfitColumns=\"true\" singleSelect=\"false\">\n");
      out.write("\t</table>\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\"\n");
      out.write("\t\tstyle=\"width: 400px; height: 280px; padding: 10px 20px\" closed=\"true\"\n");
      out.write("\t\tbuttons=\"#dlg-buttons\">\n");
      out.write("\t\t<div class=\"ftitle\">客户信息管理</div>\n");
      out.write("\t\t<form id=\"fm\" method=\"post\" action=\"updateAnnouncementAction\"\n");
      out.write("\t\t\tnovalidate>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"fitem\">\n");
      out.write("\t\t\t\t<textarea rows=8 cols=40 class=\"textarea easyui-validatebox\"\n");
      out.write("\t\t\t\t\tname=\"announcement\" id=\"announcement\"></textarea>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("<!-- \t<div id=\"toolbar\">\n");
      out.write("\t\t<a href=\"AddAnnouncement.jsp\" class=\"easyui-linkbutton\"\n");
      out.write("\t\t\ticonCls=\"icon-add\" plain=\"true\">添加客户信息</a> <a href=\"javascript:void(0)\"\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\"\n");
      out.write("\t\t\tonclick=\"destroyAnnouncement()\">删除</a>\n");
      out.write("\t</div> -->\n");
      out.write("\t<div id=\"dlg-buttons\">\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\"\n");
      out.write("\t\t\tonclick=\"saveAnnouncement()\">保存</a> <a href=\"#\"\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" iconCls=\"icon-cancel\"\n");
      out.write("\t\t\tonclick=\"javascript:$('#dlg').dialog('close')\">取消</a>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
